import { CircleUserRound, Search, ShoppingCart } from "lucide-react";
import { Link, NavLink, Outlet, useNavigate } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { selectCartCount } from "@/features/cart/cartSlice.js";
import { setSearch } from "@/features/catalog/catalogSlice.js";
export function Layout() {
  const dispatch = useDispatch(), navigate = useNavigate();
  const cartCount = useSelector(selectCartCount), search = useSelector((s) => s.catalog.filters.search), user = useSelector((s) => s.auth.user);
  return <div className="min-h-screen bg-[#efefed] md:p-8"><div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-7xl flex-col bg-paper shadow-sm"><header className="sticky top-0 z-20 border-b border-line bg-white"><div className="mx-auto grid min-h-14 max-w-6xl grid-cols-[auto_1fr_auto] items-center gap-4 px-4 md:px-6"><Link to="/" className="flex items-center gap-2 text-sm font-extrabold"><span className="h-5 w-5 rounded-full bg-forest" />PadelStore</Link><label className="mx-auto hidden w-full max-w-md items-center gap-2 rounded border border-line bg-paper px-3 py-2 text-xs text-neutral-500 sm:flex"><Search size={14} /><input value={search} onChange={(e) => { dispatch(setSearch(e.target.value)); navigate("/"); }} className="w-full bg-transparent outline-none" placeholder="Buscar palas, pelotas, ropa..." /></label><nav className="flex items-center gap-4 text-xs font-semibold"><NavLink to="/pedidos" className="hover:text-forest">Mis pedidos</NavLink><NavLink to={user ? "/pedidos" : "/login"} className="hidden hover:text-forest sm:inline">{user ? "Mi cuenta" : "Ingresar"}</NavLink><CircleUserRound size={18} className="hidden text-neutral-500 sm:block" /><NavLink to="/carrito" className="relative rounded p-1 hover:bg-paper"><ShoppingCart size={18} /><span className="absolute -right-2 -top-2 flex h-5 min-w-5 items-center justify-center rounded-full bg-forest px-1 text-[10px] text-white">{cartCount}</span></NavLink></nav></div></header><main className="flex-1"><Outlet /></main><footer className="mt-auto bg-ink px-6 py-4 text-[11px] text-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 PadelStore · Grupo 7 · UADE</span><div className="flex gap-5"><a href="#">Terminos</a><a href="#">Privacidad</a><a href="#">Contacto</a></div></div></footer></div></div>;
}
